import { getDatabase } from '@/database/database';
import { getProductById } from '@/database/repositories/productRepository';
import { rhythmConfig } from '../config/rhythmConfig';
import { normalizeRhythmMode } from '../config/rhythmModes';
import type { RhythmDecision, RhythmEvent, RhythmFeedbackType, RhythmRecommendation, RhythmSettings } from '../types/rhythm';

interface SettingsRow { mode:string;enabled:number;show_on_other_screens:number;animations_enabled:number;haptics_enabled:number;reactions_enabled:number;recommendations_enabled:number;budget_enabled:number;history_enabled:number;interface_sounds_enabled:number;onboarding_completed:number; }
const now = () => new Date().toISOString();
const safeJson = <T>(value:string,fallback:T):T => { try{return JSON.parse(value) as T;}catch{return fallback;} };

export async function loadRhythmSettings():Promise<RhythmSettings>{const db=await getDatabase();const row=await db.getFirstAsync<SettingsRow>('SELECT mode,enabled,show_on_other_screens,animations_enabled,haptics_enabled,reactions_enabled,recommendations_enabled,budget_enabled,history_enabled,interface_sounds_enabled,onboarding_completed FROM rhythm_settings WHERE id=1');return{mode:normalizeRhythmMode(row?.mode),enabled:(row?.enabled??1)===1,showOnOtherScreens:(row?.show_on_other_screens??1)===1,animationsEnabled:(row?.animations_enabled??1)===1,hapticsEnabled:(row?.haptics_enabled??1)===1,reactionsEnabled:(row?.reactions_enabled??1)===1,recommendationsEnabled:(row?.recommendations_enabled??1)===1,budgetEnabled:(row?.budget_enabled??1)===1,historyEnabled:(row?.history_enabled??1)===1,interfaceSoundsEnabled:(row?.interface_sounds_enabled??0)===1,onboardingCompleted:(row?.onboarding_completed??0)===1};}
export async function saveRhythmSettings(value:RhythmSettings){const db=await getDatabase();const stamp=now();await db.runAsync(`INSERT INTO rhythm_settings(id,mode,enabled,show_on_other_screens,animations_enabled,haptics_enabled,reactions_enabled,recommendations_enabled,budget_enabled,history_enabled,interface_sounds_enabled,onboarding_completed,created_at,updated_at) VALUES(1,?,?,?,?,?,?,?,?,?,?,?, ?,?) ON CONFLICT(id) DO UPDATE SET mode=excluded.mode,enabled=excluded.enabled,show_on_other_screens=excluded.show_on_other_screens,animations_enabled=excluded.animations_enabled,haptics_enabled=excluded.haptics_enabled,reactions_enabled=excluded.reactions_enabled,recommendations_enabled=excluded.recommendations_enabled,budget_enabled=excluded.budget_enabled,history_enabled=excluded.history_enabled,interface_sounds_enabled=excluded.interface_sounds_enabled,onboarding_completed=excluded.onboarding_completed,updated_at=excluded.updated_at`,value.mode,value.enabled?1:0,value.showOnOtherScreens?1:0,value.animationsEnabled?1:0,value.hapticsEnabled?1:0,value.reactionsEnabled?1:0,value.recommendationsEnabled?1:0,value.budgetEnabled?1:0,value.historyEnabled?1:0,value.interfaceSoundsEnabled?1:0,value.onboardingCompleted?1:0,stamp,stamp);}

export async function recordRhythmEvent(event:RhythmEvent){const db=await getDatabase();await db.runAsync('INSERT INTO rhythm_events(type,route,payload_json,created_at) VALUES(?,?,?,?)',event.type,event.route??null,JSON.stringify(event.payload??{}),event.createdAt??now());await db.runAsync(`DELETE FROM rhythm_events WHERE id NOT IN (SELECT id FROM rhythm_events ORDER BY id DESC LIMIT ?)`,rhythmConfig.historyCaps.events);}
export async function recordRhythmDecision(decision:RhythmDecision,contextHash:string){const db=await getDatabase();const stamp=decision.createdAt??now();await db.withExclusiveTransactionAsync(async(txn)=>{await txn.runAsync(`INSERT INTO rhythm_decisions(event_type,template_id,message,emotion,action,priority,kind,route,context_hash,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)`,decision.eventType,decision.templateId,decision.message,decision.visual.emotion,decision.visual.action,decision.priority,decision.kind,decision.route,contextHash,stamp);await txn.runAsync('INSERT INTO rhythm_message_history(template_id,event_type,route,shown_at) VALUES(?,?,?,?)',decision.templateId,decision.eventType,decision.route,stamp);await txn.runAsync(`DELETE FROM rhythm_message_history WHERE id NOT IN (SELECT id FROM rhythm_message_history ORDER BY id DESC LIMIT ?)`,rhythmConfig.historyCaps.messages);});}
export async function loadRecentRhythmState(){const db=await getDatabase();const since=new Date(Date.now()-24*60*60*1000).toISOString();const [messages,rejections,last]=await Promise.all([db.getAllAsync<{template_id:string}>('SELECT template_id FROM rhythm_message_history WHERE shown_at>=? ORDER BY shown_at DESC',since),db.getFirstAsync<{count:number}>(`SELECT COUNT(*) count FROM rhythm_feedback WHERE feedback_type IN ('dismissed','replaced') AND created_at>=?`,since),db.getFirstAsync<{shown_at:string}>('SELECT shown_at FROM rhythm_message_history ORDER BY shown_at DESC LIMIT 1')]);return{recentTemplateIds:messages.map(i=>i.template_id),recentRejections:rejections?.count??0,lastInitiativeAt:last?.shown_at??null};}

export async function getCooldown(key:string){const db=await getDatabase();return db.getFirstAsync<{until_at:string;rejection_count:number}>('SELECT until_at,rejection_count FROM rhythm_cooldowns WHERE cooldown_key=?',key);}
export async function setCooldown(key:string,untilAt:string,rejectionDelta=0){const db=await getDatabase();await db.runAsync(`INSERT INTO rhythm_cooldowns(cooldown_key,until_at,rejection_count,updated_at) VALUES(?,?,?,?) ON CONFLICT(cooldown_key) DO UPDATE SET until_at=excluded.until_at,rejection_count=MAX(0,rhythm_cooldowns.rejection_count+?),updated_at=excluded.updated_at`,key,untilAt,Math.max(0,rejectionDelta),now(),rejectionDelta);}

export async function saveRhythmRecommendations(items:RhythmRecommendation[]){if(!items.length)return;const db=await getDatabase();const stamp=now();await db.withExclusiveTransactionAsync(async(txn)=>{for(const item of items)await txn.runAsync(`INSERT INTO rhythm_recommendations(recommendation_key,context_hash,payload_json,status,score,created_at,updated_at) VALUES(?,?,?,'shown',?,?,?)`,item.id,item.contextHash,JSON.stringify(item),item.score,stamp,stamp);await txn.runAsync(`DELETE FROM rhythm_recommendations WHERE id NOT IN (SELECT id FROM rhythm_recommendations ORDER BY id DESC LIMIT ?)`,rhythmConfig.historyCaps.recommendations);});}
export async function loadCachedRecommendations(contextHash:string){const db=await getDatabase();const rows=await db.getAllAsync<{payload_json:string}>('SELECT payload_json FROM rhythm_recommendations WHERE context_hash=? ORDER BY score DESC,created_at DESC LIMIT 5',contextHash);const parsed=rows.map(row=>safeJson<RhythmRecommendation|null>(row.payload_json,null)).filter((item):item is RhythmRecommendation=>item!==null);return Promise.all(parsed.map(async recommendation=>{const canonical=await Promise.all(recommendation.items.map(async item=>{const product=await getProductById(item.product.id);return product?{...item,product}:null;}));const unique=[...new Map(canonical.filter((item):item is NonNullable<typeof item>=>item!==null).map(item=>[item.product.id,item])).values()];return{...recommendation,items:unique};}));}

export async function recordRhythmFeedback(type:RhythmFeedbackType,options:{recommendationKey?:string;productIds?:number[];payload?:Record<string,unknown>;trackPreference?:boolean}={}){const db=await getDatabase();const weight=rhythmConfig.feedbackWeights[type];const stamp=now();await db.withExclusiveTransactionAsync(async(txn)=>{const ids=options.productIds?.length?options.productIds:[null];for(const id of ids){await txn.runAsync('INSERT INTO rhythm_feedback(recommendation_key,product_id,feedback_type,weight,payload_json,created_at) VALUES(?,?,?,?,?,?)',options.recommendationKey??null,id,type,weight,JSON.stringify(options.payload??{}),stamp);if(id!=null&&options.trackPreference!==false)await txn.runAsync(`INSERT INTO rhythm_preferences(entity_type,entity_id,weight,last_decayed_at,updated_at) VALUES('product',?,?,?,?) ON CONFLICT(entity_type,entity_id) DO UPDATE SET weight=rhythm_preferences.weight+excluded.weight,updated_at=excluded.updated_at`,String(id),weight,stamp,stamp);}await txn.runAsync(`DELETE FROM rhythm_feedback WHERE id NOT IN (SELECT id FROM rhythm_feedback ORDER BY id DESC LIMIT ?)`,rhythmConfig.historyCaps.feedback);});}
export async function loadProductPreferenceWeights(){const db=await getDatabase();const rows=await db.getAllAsync<{entity_id:string;weight:number;last_decayed_at:string}>(`SELECT entity_id,weight,last_decayed_at FROM rhythm_preferences WHERE entity_type='product'`);const result:Record<number,number>={};const stamp=now();for(const row of rows){const days=Math.max(0,(Date.now()-new Date(row.last_decayed_at).getTime())/86400000);const periods=Math.floor(days/rhythmConfig.preferenceDecayDays);const weight=periods?row.weight*Math.pow(.85,periods):row.weight;result[Number(row.entity_id)]=weight;if(periods)await db.runAsync(`UPDATE rhythm_preferences SET weight=?,last_decayed_at=?,updated_at=? WHERE entity_type='product' AND entity_id=?`,weight,stamp,stamp,row.entity_id);}return result;}

export async function recordMealPlanRun(value:{contextHash:string;mode:string;candidateCount:number;durationMs:number;result:unknown}){const db=await getDatabase();await db.runAsync('INSERT INTO meal_plan_runs(context_hash,mode,candidate_count,duration_ms,result_json,created_at) VALUES(?,?,?,?,?,?)',value.contextHash,value.mode,value.candidateCount,value.durationMs,JSON.stringify(value.result),now());}
export async function resetRhythmLearning(){const db=await getDatabase();await db.execAsync('DELETE FROM rhythm_events; DELETE FROM rhythm_decisions; DELETE FROM rhythm_recommendations; DELETE FROM rhythm_feedback; DELETE FROM rhythm_preferences; DELETE FROM rhythm_cooldowns; DELETE FROM rhythm_message_history; DELETE FROM meal_plan_runs;');}
export async function resetRhythmPreferences(){const db=await getDatabase();await db.execAsync('DELETE FROM rhythm_recommendations; DELETE FROM rhythm_feedback; DELETE FROM rhythm_preferences; DELETE FROM meal_plan_runs;');}
export async function clearRhythmHintHistory(){const db=await getDatabase();await db.execAsync('DELETE FROM rhythm_events; DELETE FROM rhythm_decisions; DELETE FROM rhythm_cooldowns; DELETE FROM rhythm_message_history;');}
export async function loadRhythmDiagnostics(){const db=await getDatabase();const tables=['rhythm_events','rhythm_decisions','rhythm_recommendations','rhythm_feedback','rhythm_preferences','rhythm_message_history','meal_plan_runs'];const counts:Record<string,number>={};for(const table of tables){const row=await db.getFirstAsync<{count:number}>(`SELECT COUNT(*) count FROM ${table}`);counts[table]=row?.count??0;}return counts;}

