import type { BudgetSettings, MealType, Product, ProfileDraft } from '@/types/domain';

export interface NutritionRemainder { calories: number; proteinG: number; fatG: number; carbsG: number; }
export interface RemainderMatchItem { product: Product; quantityG: number; servings: number; calories: number; proteinG: number; fatG: number; carbsG: number; price: number; }
export interface RemainderMatch { id: string; label: string; score: number; items: RemainderMatchItem[]; total: NutritionRemainder & { price: number }; reasons: string[]; }
export interface RemainderOptions { profile: ProfileDraft; mealType: MealType; budget?: BudgetSettings | null; usedProductIds?: number[]; maxCandidates?: number; }

const restrictionTerms: Record<ProfileDraft['restrictions'][number], string[]> = { lactoseFree: ['milk','лактоз','молок'], glutenFree: ['gluten','wheat','глютен','пшениц'], sugarFree: ['sugar','сахар'], nutFree: ['nut','peanut','орех','арахис'] };
function restricted(product: Product, profile: ProfileDraft) { const text = [...product.allergens, product.ingredients ?? ''].join(' ').toLocaleLowerCase('ru-RU'); if (profile.restrictions.some((item) => restrictionTerms[item].some((term) => text.includes(term)))) return true; return profile.dietPreference === 'vegetarian' && [...product.dietTags, product.category].join(' ').toLocaleLowerCase('ru-RU').match(/meat|fish|мяс|рыб/); }
function itemFor(product: Product, remaining: NutritionRemainder): RemainderMatchItem { const servingCalories = Math.max(1, product.calories); const desired = Math.max(0.5, Math.min(2, remaining.calories / servingCalories)); const servings = Math.round(desired * 4) / 4; return { product, servings, quantityG: product.servingSizeG * servings, calories: product.calories * servings, proteinG: (product.proteinG ?? 0) * servings, fatG: (product.fatG ?? 0) * servings, carbsG: (product.carbsG ?? 0) * servings, price: product.price * servings }; }
function total(items: RemainderMatchItem[]) { return items.reduce((sum, item) => ({ calories: sum.calories + item.calories, proteinG: sum.proteinG + item.proteinG, fatG: sum.fatG + item.fatG, carbsG: sum.carbsG + item.carbsG, price: sum.price + item.price }), { calories: 0, proteinG: 0, fatG: 0, carbsG: 0, price: 0 }); }
function distance(value: number, target: number, floor: number) { return Math.abs(value - Math.max(0, target)) / Math.max(floor, Math.abs(target)); }
function score(items: RemainderMatchItem[], remaining: NutritionRemainder, options: RemainderOptions) { const result = total(items); let value = 100 - distance(result.calories, remaining.calories, 250) * 42 - distance(result.proteinG, remaining.proteinG, 25) * 30 - distance(result.fatG, remaining.fatG, 15) * 10 - distance(result.carbsG, remaining.carbsG, 35) * 12; if (items.every((item) => item.product.mealTags.includes(options.mealType))) value += 9; if (items.some((item) => item.product.goalTags.includes(options.profile.goal))) value += 7; if (items.some((item) => options.usedProductIds?.includes(item.product.id))) value -= 9; if (items.some((item) => item.product.dataStatus === 'demo' || item.product.dataStatus === 'community')) value -= 3; const budget = options.budget?.includeInRecommendations ? options.budget.perMealBudget : null; if (budget != null) value += result.price <= budget ? 12 : -Math.min(35, (result.price - budget) / Math.max(1, budget) * 35); return value; }
function sensiblePair(a: Product, b: Product) { if (a.id === b.id || a.category === b.category) return false; const beverage = (value: Product) => /напит|молоко|water|drink/i.test(value.category); return !(beverage(a) && beverage(b)); }

export function calculateRemainder(target: NutritionRemainder, consumed: NutritionRemainder): NutritionRemainder { return { calories: Math.max(0, target.calories - consumed.calories), proteinG: Math.max(0, target.proteinG - consumed.proteinG), fatG: Math.max(0, target.fatG - consumed.fatG), carbsG: Math.max(0, target.carbsG - consumed.carbsG) }; }

export function matchRemainder(products: Product[], remaining: NutritionRemainder, options: RemainderOptions): RemainderMatch[] {
  const filtered = products.filter((product) => product.isAvailable && product.calories > 0 && !restricted(product, options.profile)); const rankedSingles = filtered.map((product) => [product, score([itemFor(product, remaining)], remaining, options)] as const).sort((a,b) => b[1]-a[1]).slice(0, options.maxCandidates ?? 24);
  const candidates: RemainderMatch[] = rankedSingles.map(([product]) => { const items=[itemFor(product,remaining)]; const value=score(items,remaining,options); return { id:`single-${product.id}`, label:'Вариант', score:value, items, total:total(items), reasons:[] }; });
  for (let a=0;a<Math.min(12,rankedSingles.length);a+=1) for(let b=a+1;b<Math.min(16,rankedSingles.length);b+=1){ const [first]=rankedSingles[a]; const [second]=rankedSingles[b]; if(!sensiblePair(first,second))continue; const half={...remaining,calories:remaining.calories/2,proteinG:remaining.proteinG/2,fatG:remaining.fatG/2,carbsG:remaining.carbsG/2}; const items=[itemFor(first,half),itemFor(second,half)]; candidates.push({id:`pair-${first.id}-${second.id}`,label:'Сочетание',score:score(items,remaining,options)+4,items,total:total(items),reasons:['Две позиции без полного перебора каталога']}); }
  const sorted=candidates.sort((a,b)=>b.score-a.score).slice(0,12); const picks:RemainderMatch[]=[]; const add=(label:string,predicate:(item:RemainderMatch)=>boolean)=>{const found=sorted.find((item)=>predicate(item)&&!picks.includes(item));if(found)picks.push({...found,label});}; add('Лучшее совпадение',()=>true); add('Больше белка',(item)=>item.total.proteinG>=remaining.proteinG*.8); add('Меньше калорий',(item)=>item.total.calories<=remaining.calories); add('Из «Точки Роста»',(item)=>item.items.some(({product})=>product.sourceType==='tochka_rosta')); add('Из обычных продуктов',(item)=>item.items.every(({product})=>product.sourceType!=='tochka_rosta')); const budget=options.budget?.perMealBudget; if(budget)add(`До ${Math.round(budget)} ₽`,(item)=>item.total.price<=budget); return picks.slice(0,6);
}
