import type { BudgetSettings, MealType, NutritionResult, Product, ProfileDraft, WeeklyPlan, WeeklyPlanSettings } from '@/types/domain';
import { createStableUuid } from './uuid';
import { scoreProductForMeal } from './mealPlanner';
import { shiftLocalDate } from './calendar';

const sequences: Record<3|4|5, MealType[]> = { 3:['breakfast','lunch','dinner'], 4:['breakfast','lunch','snack','dinner'], 5:['breakfast','snack','lunch','snack','dinner'] };
function allowedForMode(product:Product,mode:WeeklyPlanSettings['mode']){if(mode==='tochka')return product.sourceType==='tochka_rosta';if(mode==='home')return product.sourceType!=='tochka_rosta';if(mode==='highProtein')return (product.proteinG??0)>=15;if(mode==='quick')return product.sourceType==='tochka_rosta'||product.category==='Готовые блюда';return true;}
export function generateWeeklyPlan(weekStartDate:string,products:Product[],target:NutritionResult,profile:ProfileDraft,settings:WeeklyPlanSettings,budget?:BudgetSettings|null):WeeklyPlan { const counts=new Map<number,number>(); const items:WeeklyPlan['items']=[]; for(let day=0;day<7;day+=1){const date=shiftLocalDate(weekStartDate,day);for(const meal of sequences[settings.mealsPerDay]){const ranked=products.filter((p)=>allowedForMode(p,settings.mode)&&(counts.get(p.id)??0)<settings.maxRepeats).sort((a,b)=>{let delta=scoreProductForMeal(b,meal,target,profile,new Set())-scoreProductForMeal(a,meal,target,profile,new Set());if(settings.mode==='budget')delta+=(a.price-b.price)/10;return delta;});const product=ranked[(day+items.length)%Math.max(1,Math.min(5,ranked.length))]??ranked[0];if(!product)throw new Error('Недостаточно подходящих продуктов для недели');counts.set(product.id,(counts.get(product.id)??0)+1);items.push({uuid:createStableUuid(),date,product,mealType:meal,amountG:product.servingSizeG,servings:1,estimatedCost:product.price,isAddedToDiary:false});}}
  const estimatedCost=items.reduce((sum,item)=>sum+item.estimatedCost,0);return{id:undefined,uuid:createStableUuid(),weekStartDate,targetBudget:budget?.weeklyBudget??null,estimatedCost,status:'planned',settings,items}; }
export function moveWeeklyItem(plan:WeeklyPlan,itemUuid:string,targetDate:string){return{...plan,items:plan.items.map((item)=>item.uuid===itemUuid?{...item,date:targetDate}:item)};}
export function copyWeeklyDay(plan:WeeklyPlan,sourceDate:string,targetDate:string){const retained=plan.items.filter((item)=>item.date!==targetDate);const copied=plan.items.filter((item)=>item.date===sourceDate).map((item)=>({...item,uuid:createStableUuid(),date:targetDate,isAddedToDiary:false}));return{...plan,items:[...retained,...copied]};}
