import { calculateStreaks } from '@/services/flowCalculator';
import { getLocalDateKey } from '@/utils/date';
import { getDatabase } from '../database';
import { ensureCatalogCanonicalization } from './catalogCanonicalizationRepository';
import { seedDatabase } from '../seed';

export async function createTestStreak(days: 3 | 7 | 14 | 30) {
  const db = await getDatabase(); const today = new Date(); const now = new Date().toISOString(); const dates = Array.from({ length: days }, (_, index) => { const date = new Date(today); date.setDate(date.getDate() - index); return getLocalDateKey(date); }).reverse();
  await db.withExclusiveTransactionAsync(async (txn) => { for (const date of dates) { await txn.runAsync(`INSERT INTO diary_days (date, target_calories, consumed_calories, is_completed, created_at, updated_at, target_protein_g, target_fat_g, target_carbs_g, consumed_protein_g, consumed_fat_g, consumed_carbs_g, completed_at) VALUES (?, 0, 0, 1, ?, ?, 0, 0, 0, 0, 0, 0, ?) ON CONFLICT(date) DO UPDATE SET is_completed=1, completed_at=excluded.completed_at, updated_at=excluded.updated_at`, date, now, now, now); await txn.runAsync(`INSERT INTO flow_history (date, was_completed, streak_after_completion, created_at) VALUES (?, 1, ?, ?) ON CONFLICT(date) DO UPDATE SET was_completed=1, streak_after_completion=excluded.streak_after_completion`, date, dates.indexOf(date) + 1, now); } const streak = calculateStreaks(dates, getLocalDateKey()); await txn.runAsync('UPDATE flow_state SET current_streak=?, longest_streak=MAX(longest_streak, ?), last_completed_date=?, updated_at=? WHERE id=1', streak.currentStreak, streak.longestStreak, streak.lastCompletedDate, now); });
}
export async function clearDiaryForDevelopment() { const db = await getDatabase(); await db.execAsync('DELETE FROM diary_entries; DELETE FROM diary_days;'); }
export async function clearFlowForDevelopment() { const db = await getDatabase(); await db.execAsync(`DELETE FROM flow_history; UPDATE diary_days SET is_completed=0, completed_at=NULL; UPDATE flow_state SET current_streak=0, longest_streak=0, last_completed_date=NULL, updated_at=CURRENT_TIMESTAMP WHERE id=1;`); }
export async function reseedForDevelopment() { const db=await getDatabase();await db.withExclusiveTransactionAsync(async txn=>seedDatabase(txn));await ensureCatalogCanonicalization(db,true); }
export async function recalculateAllDiaryAggregates() { const db = await getDatabase(); await db.runAsync(`UPDATE diary_days SET consumed_calories=COALESCE((SELECT SUM(calories) FROM diary_entries WHERE diary_day_id=diary_days.id AND deleted_at IS NULL),0), consumed_protein_g=COALESCE((SELECT SUM(protein_g) FROM diary_entries WHERE diary_day_id=diary_days.id AND deleted_at IS NULL),0), consumed_fat_g=COALESCE((SELECT SUM(fat_g) FROM diary_entries WHERE diary_day_id=diary_days.id AND deleted_at IS NULL),0), consumed_carbs_g=COALESCE((SELECT SUM(carbs_g) FROM diary_entries WHERE diary_day_id=diary_days.id AND deleted_at IS NULL),0), updated_at=?`, new Date().toISOString()); }
export async function createDemoV3Data() {
  const db = await getDatabase(); const now = new Date().toISOString(); const today = new Date();
  await db.withExclusiveTransactionAsync(async (txn) => {
    for (let index = 20; index >= 0; index -= 1) { const date = new Date(today); date.setDate(date.getDate() - index * 3); await txn.runAsync(`INSERT INTO weight_logs(date,weight_kg,note,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(date) DO UPDATE SET weight_kg=excluded.weight_kg,note=excluded.note,updated_at=excluded.updated_at`, getLocalDateKey(date), 82 - (20 - index) * 0.16, 'Демо APP v0.3', now, now); }
    for (const amount of [250, 300, 250, 500]) await txn.runAsync('INSERT INTO water_entries(date,amount_ml,created_at) VALUES(?,?,?)', getLocalDateKey(), amount, now);
    for (const query of ['гречка', 'куриная грудка', 'йогурт']) await txn.runAsync(`INSERT INTO search_history(query,use_count,last_used_at) VALUES(?,1,?) ON CONFLICT(query) DO UPDATE SET use_count=use_count+1,last_used_at=excluded.last_used_at`, query, now);
    const existing = await txn.getFirstAsync<{ id: number }>("SELECT id FROM meal_templates WHERE name='Демо-завтрак'");
    if (!existing) { const template = await txn.runAsync("INSERT INTO meal_templates(name,default_meal_type,created_at,updated_at) VALUES('Демо-завтрак','breakfast',?,?)", now, now); const products = await txn.getAllAsync<{ id: number; name: string; serving_size_g: number }>('SELECT id,name,serving_size_g FROM products WHERE deleted_at IS NULL LIMIT 2'); for (const product of products) await txn.runAsync("INSERT INTO meal_template_items(template_id,product_id,product_name_snapshot,meal_type,servings,quantity_g,created_at) VALUES(?,?,?,'breakfast',1,?,?)", Number(template.lastInsertRowId), product.id, product.name, product.serving_size_g, now); }
  });
}
export async function clearV3DemoData() { const db = await getDatabase(); await db.execAsync("DELETE FROM weight_logs WHERE note='Демо APP v0.3'; DELETE FROM water_entries; DELETE FROM search_history; DELETE FROM meal_template_items WHERE template_id IN (SELECT id FROM meal_templates WHERE name='Демо-завтрак'); DELETE FROM meal_templates WHERE name='Демо-завтрак';"); }
export async function loadCatalogDataQualityReport() {
  const db = await getDatabase();
  const [total, active, merged, technical, duplicateCanonical, missingCategories, invalidMacros, needsReview, migration] = await Promise.all([
    db.getFirstAsync<{ count: number }>('SELECT COUNT(*) AS count FROM products WHERE deleted_at IS NULL'),
    db.getFirstAsync<{ count: number }>('SELECT COUNT(*) AS count FROM products WHERE deleted_at IS NULL AND is_active=1'),
    db.getFirstAsync<{ count: number }>('SELECT COUNT(*) AS count FROM products WHERE merged_into_id IS NOT NULL'),
    db.getFirstAsync<{ count: number }>("SELECT COUNT(*) AS count FROM products WHERE deleted_at IS NULL AND is_active=1 AND lower(name) LIKE '%вариант %'"),
    db.getFirstAsync<{ count: number }>(`SELECT COUNT(*) AS count FROM (SELECT canonical_key FROM products WHERE deleted_at IS NULL AND is_active=1 AND canonical_key IS NOT NULL GROUP BY canonical_key HAVING COUNT(*)>1)`),
    db.getFirstAsync<{ count: number }>("SELECT COUNT(*) AS count FROM products WHERE deleted_at IS NULL AND is_active=1 AND trim(category)=''"),
    db.getFirstAsync<{ count: number }>(`SELECT COUNT(*) AS count FROM products WHERE deleted_at IS NULL AND is_active=1 AND (calories_per_100g<0 OR protein_per_100g<0 OR fat_per_100g<0 OR carbs_per_100g<0)`),
    db.getFirstAsync<{ count: number }>("SELECT COUNT(*) AS count FROM products WHERE deleted_at IS NULL AND review_status='needs_review'"),
    db.getFirstAsync<{ before_count: number; after_count: number; technical_names_before: number; technical_names_after: number }>("SELECT before_count,after_count,technical_names_before,technical_names_after FROM catalog_migration_reports WHERE migration_key='catalog-v8'"),
  ]);
  return { total: total?.count ?? 0, active: active?.count ?? 0, merged: merged?.count ?? 0, technical: technical?.count ?? 0, duplicateCanonical: duplicateCanonical?.count ?? 0, missingCategories: missingCategories?.count ?? 0, invalidMacros: invalidMacros?.count ?? 0, needsReview: needsReview?.count ?? 0, migration: migration ?? null };
}
export async function inspectDevelopmentDatabase() { const db = await getDatabase(); const [version, productCount, entryCount, coded, duplicateCodes, weights, water, templates, searches, pageCount, pageSize] = await Promise.all([db.getFirstAsync<{ user_version: number }>('PRAGMA user_version'), db.getFirstAsync<{ count: number }>('SELECT COUNT(*) AS count FROM products WHERE deleted_at IS NULL'), db.getFirstAsync<{ count: number }>('SELECT COUNT(*) AS count FROM diary_entries WHERE deleted_at IS NULL'), db.getFirstAsync<{ count: number }>("SELECT COUNT(*) AS count FROM products WHERE barcode IS NOT NULL OR qr_code IS NOT NULL"), db.getFirstAsync<{ count: number }>(`SELECT COUNT(*) AS count FROM (SELECT COALESCE(barcode, qr_code) AS code FROM products WHERE barcode IS NOT NULL OR qr_code IS NOT NULL GROUP BY code HAVING COUNT(*)>1)`), db.getFirstAsync<{ count: number }>('SELECT COUNT(*) AS count FROM weight_logs'), db.getFirstAsync<{ count: number }>('SELECT COUNT(*) AS count FROM water_entries'), db.getFirstAsync<{ count: number }>('SELECT COUNT(*) AS count FROM meal_templates'), db.getFirstAsync<{ count: number }>('SELECT COUNT(*) AS count FROM search_history'), db.getFirstAsync<{ page_count: number }>('PRAGMA page_count'), db.getFirstAsync<{ page_size: number }>('PRAGMA page_size')]); return { version: version?.user_version ?? 0, products: productCount?.count ?? 0, entries: entryCount?.count ?? 0, coded: coded?.count ?? 0, duplicateCodes: duplicateCodes?.count ?? 0, weights: weights?.count ?? 0, water: water?.count ?? 0, templates: templates?.count ?? 0, searches: searches?.count ?? 0, databaseBytes: (pageCount?.page_count ?? 0) * (pageSize?.page_size ?? 0) }; }
