import { calculateStreaks } from '@/services/flowCalculator';
import { getLocalDateKey } from '@/utils/date';
import { getDatabase } from '../database';
import { seedDatabase } from '../seed';

export async function createTestStreak(days: 3 | 7 | 14) {
  const db = await getDatabase(); const today = new Date(); const now = new Date().toISOString(); const dates = Array.from({ length: days }, (_, index) => { const date = new Date(today); date.setDate(date.getDate() - index); return getLocalDateKey(date); }).reverse();
  await db.withExclusiveTransactionAsync(async (txn) => { for (const date of dates) { await txn.runAsync(`INSERT INTO diary_days (date, target_calories, consumed_calories, is_completed, created_at, updated_at, target_protein_g, target_fat_g, target_carbs_g, consumed_protein_g, consumed_fat_g, consumed_carbs_g, completed_at) VALUES (?, 0, 0, 1, ?, ?, 0, 0, 0, 0, 0, 0, ?) ON CONFLICT(date) DO UPDATE SET is_completed=1, completed_at=excluded.completed_at, updated_at=excluded.updated_at`, date, now, now, now); await txn.runAsync(`INSERT INTO flow_history (date, was_completed, streak_after_completion, created_at) VALUES (?, 1, ?, ?) ON CONFLICT(date) DO UPDATE SET was_completed=1, streak_after_completion=excluded.streak_after_completion`, date, dates.indexOf(date) + 1, now); } const streak = calculateStreaks(dates, getLocalDateKey()); await txn.runAsync('UPDATE flow_state SET current_streak=?, longest_streak=MAX(longest_streak, ?), last_completed_date=?, updated_at=? WHERE id=1', streak.currentStreak, streak.longestStreak, streak.lastCompletedDate, now); });
}
export async function clearDiaryForDevelopment() { const db = await getDatabase(); await db.execAsync('DELETE FROM diary_entries; DELETE FROM diary_days;'); }
export async function clearFlowForDevelopment() { const db = await getDatabase(); await db.execAsync(`DELETE FROM flow_history; UPDATE diary_days SET is_completed=0, completed_at=NULL; UPDATE flow_state SET current_streak=0, longest_streak=0, last_completed_date=NULL, updated_at=CURRENT_TIMESTAMP WHERE id=1;`); }
export async function reseedForDevelopment() { await seedDatabase(await getDatabase()); }
export async function recalculateAllDiaryAggregates() { const db = await getDatabase(); await db.runAsync(`UPDATE diary_days SET consumed_calories=COALESCE((SELECT SUM(calories) FROM diary_entries WHERE diary_day_id=diary_days.id),0), consumed_protein_g=COALESCE((SELECT SUM(protein_g) FROM diary_entries WHERE diary_day_id=diary_days.id),0), consumed_fat_g=COALESCE((SELECT SUM(fat_g) FROM diary_entries WHERE diary_day_id=diary_days.id),0), consumed_carbs_g=COALESCE((SELECT SUM(carbs_g) FROM diary_entries WHERE diary_day_id=diary_days.id),0), updated_at=?`, new Date().toISOString()); }
export async function inspectDevelopmentDatabase() { const db = await getDatabase(); const version = await db.getFirstAsync<{ user_version: number }>('PRAGMA user_version'); const productCount = await db.getFirstAsync<{ count: number }>('SELECT COUNT(*) AS count FROM products WHERE deleted_at IS NULL'); const entryCount = await db.getFirstAsync<{ count: number }>('SELECT COUNT(*) AS count FROM diary_entries'); const coded = await db.getFirstAsync<{ count: number }>("SELECT COUNT(*) AS count FROM products WHERE barcode IS NOT NULL OR qr_code IS NOT NULL"); const duplicateCodes = await db.getFirstAsync<{ count: number }>(`SELECT COUNT(*) AS count FROM (SELECT COALESCE(barcode, qr_code) AS code FROM products WHERE barcode IS NOT NULL OR qr_code IS NOT NULL GROUP BY code HAVING COUNT(*)>1)`); return { version: version?.user_version ?? 0, products: productCount?.count ?? 0, entries: entryCount?.count ?? 0, coded: coded?.count ?? 0, duplicateCodes: duplicateCodes?.count ?? 0 }; }
