import { createStableUuid } from '@/services/uuid';
import type { ResearchSession } from '@/types/domain';
import { getDatabase } from '../database';
import { serializeResearchCsv, type ResearchExportRow } from '@/services/researchExport';
export async function startResearchSession(){const db=await getDatabase();const now=new Date().toISOString();const uuid=createStableUuid();const result=await db.runAsync('INSERT INTO research_sessions(uuid,started_at,created_at) VALUES(?,?,?)',uuid,now,now);return{id:Number(result.lastInsertRowId),uuid,startedAt:now};}
export async function recordResearchEvent(sessionId:number,eventType:string,screen:string,metadata:Record<string,unknown>={}){const db=await getDatabase();await db.runAsync('INSERT INTO research_events(session_id,event_type,screen,metadata_json,created_at) VALUES(?,?,?,?,?)',sessionId,eventType,screen,JSON.stringify(metadata),new Date().toISOString());}
export async function completeResearchSession(sessionId:number,survey:Record<string,unknown>){const db=await getDatabase();const row=await db.getFirstAsync<{started_at:string}>('SELECT started_at FROM research_sessions WHERE id=?',sessionId);if(!row)throw new Error('Исследовательская сессия не найдена');const now=new Date().toISOString();const duration=Math.max(0,Math.round((Date.parse(now)-Date.parse(row.started_at))/1000));await db.runAsync('UPDATE research_sessions SET completed_at=?,duration_seconds=?,survey_json=? WHERE id=?',now,duration,JSON.stringify(survey),sessionId);}
export async function loadResearchSessions():Promise<ResearchSession[]>{const db=await getDatabase();const rows=await db.getAllAsync<{id:number;uuid:string;started_at:string;completed_at:string|null;duration_seconds:number|null;survey_json:string|null}>('SELECT * FROM research_sessions ORDER BY started_at DESC');return rows.map((row)=>({id:row.id,uuid:row.uuid,startedAt:row.started_at,completedAt:row.completed_at,durationSeconds:row.duration_seconds,survey:row.survey_json?JSON.parse(row.survey_json) as Record<string,unknown>:null}));}
export async function exportResearchCsv(){const db=await getDatabase();const rows=await db.getAllAsync<ResearchExportRow>(`SELECT s.uuid AS session_uuid,s.started_at,s.completed_at,s.duration_seconds,e.event_type,e.screen,e.metadata_json FROM research_sessions s LEFT JOIN research_events e ON e.session_id=s.id ORDER BY s.started_at,e.created_at`);return serializeResearchCsv(rows);}
export async function exportResearchJson(){const db=await getDatabase();const[sessions,events]=await Promise.all([db.getAllAsync<Record<string,string|number|null>>('SELECT * FROM research_sessions ORDER BY started_at'),db.getAllAsync<Record<string,string|number|null>>('SELECT * FROM research_events ORDER BY created_at')]);return{format:'tochka-rosta-research',version:1,createdAt:new Date().toISOString(),sessions,events};}
