import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { Pressable, StyleSheet, View } from 'react-native';
import { AppText } from '@/components/AppText';
import { FilterChip } from '@/components/FilterChip';
import { GlassCard } from '@/components/GlassCard';
import { TabScreen } from '@/components/TabScreen';
import { mealLabels } from '@/constants/options';
import { loadHistoryAnalytics } from '@/database/repositories/analyticsRepository';
import { colors, radii, spacing } from '@/theme/tokens';
import type { HistoryAnalytics, MealType } from '@/types/domain';

export default function AnalyticsScreen() { const [period, setPeriod] = useState<7 | 30>(7); const [data, setData] = useState<HistoryAnalytics | null>(null); useEffect(() => { void loadHistoryAnalytics(period).then(setData); }, [period]); const max = Math.max(1, ...(data?.caloriesByDay.map((item) => item.calories) ?? [1])); return <TabScreen title="История и аналитика" subtitle="Только данные этого устройства" headerRight={<Pressable style={styles.close} onPress={() => router.back()}><AppText>×</AppText></Pressable>}><View style={styles.chips}><FilterChip label="7 дней" selected={period === 7} onPress={() => setPeriod(7)}/><FilterChip label="30 дней" selected={period === 30} onPress={() => setPeriod(30)}/></View>
  {!data?.entryCount ? <GlassCard style={styles.empty}><AppText variant="heading">История ещё формируется</AppText><AppText tone="secondary">Добавляй блюда и закрывай дни — здесь появятся средние значения и динамика.</AppText></GlassCard> : <><View style={styles.stats}><GlassCard variant="compact" style={styles.stat}><AppText variant="title">{Math.round(data.averageCalories)}</AppText><AppText variant="caption" tone="secondary">ккал в среднем</AppText></GlassCard><GlassCard variant="compact" style={styles.stat}><AppText variant="title">{data.completedDays}</AppText><AppText variant="caption" tone="secondary">дней закрыто</AppText></GlassCard></View><GlassCard><AppText variant="heading">Калории по дням</AppText><View style={styles.chart}>{data.caloriesByDay.map((item) => <View key={item.date} style={styles.barSlot}><View style={[styles.bar, { height: Math.max(4, item.calories / max * 120) }, item.completed && styles.barDone]}/><AppText variant="caption" tone="muted">{item.date.slice(8)}</AppText></View>)}</View></GlassCard><GlassCard><AppText variant="heading">Приёмы пищи</AppText>{(Object.keys(mealLabels) as MealType[]).map((meal) => <View key={meal} style={styles.distribution}><AppText tone="secondary">{mealLabels[meal]}</AppText><AppText>{data.mealDistribution[meal]}</AppText></View>)}</GlassCard><GlassCard variant="compact"><AppText variant="heading">За период</AppText><AppText tone="secondary">Записей: {data.entryCount} · средний белок: {Math.round(data.averageProteinG)} г</AppText><AppText tone="secondary">Чаще всего: {data.mostFrequentProduct ?? '—'}</AppText><AppText tone="secondary">Лучшая серия: {data.longestStreak} дней</AppText></GlassCard></>}
  </TabScreen>; }
const styles = StyleSheet.create({ close: { width: 42, height: 42, borderRadius: radii.pill, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface }, chips: { flexDirection: 'row', gap: spacing.sm }, empty: { gap: spacing.sm }, stats: { flexDirection: 'row', gap: spacing.sm }, stat: { flex: 1 }, chart: { height: 160, marginTop: spacing.md, flexDirection: 'row', alignItems: 'flex-end', gap: 5 }, barSlot: { flex: 1, alignItems: 'center', gap: 4 }, bar: { width: '70%', borderRadius: radii.sm, backgroundColor: colors.greenDark }, barDone: { backgroundColor: colors.greenPrimary }, distribution: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: spacing.sm, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: colors.glassBorder } });
