import { useEffect, useState } from 'react';
import { router } from 'expo-router';
import { Pressable, StyleSheet, View } from 'react-native';
import { AppText } from '@/components/AppText';
import { GlassCard } from '@/components/GlassCard';
import { TabScreen } from '@/components/TabScreen';
import { getLocalDataSummary } from '@/database/repositories/dataRepository';
import { colors, radii, spacing } from '@/theme/tokens';

const names: Record<string, string> = { tochka_rosta: 'Точка Роста', usda: 'USDA FoodData Central', open_food_facts: 'Open Food Facts', user_product: 'Мои продукты', user_recipe: 'Мои рецепты' };
export default function DataSourcesScreen() { const [summary, setSummary] = useState<Awaited<ReturnType<typeof getLocalDataSummary>> | null>(null); useEffect(() => { void getLocalDataSummary().then(setSummary); }, []); return <TabScreen title="Источники данных" subtitle="Откуда берётся пищевая ценность" headerRight={<Pressable style={styles.close} onPress={() => router.back()}><AppText>×</AppText></Pressable>}><GlassCard variant="accent"><AppText variant="heading">Локальная база</AppText><AppText tone="secondary">{summary?.products ?? '—'} продуктов · {summary?.custom ?? '—'} создано пользователем</AppText><AppText variant="caption" tone="muted">Каталог, дневник и история доступны без сети. Внешний запрос выполняется только после сканирования неизвестного штрихкода.</AppText></GlassCard>{summary?.sources.map((source) => <GlassCard key={source.source_type} variant="compact"><View style={styles.row}><View style={styles.copy}><AppText style={styles.bold}>{names[source.source_type] ?? source.source_type}</AppText><AppText variant="caption" tone="secondary">{source.count} записей</AppText></View><AppText tone="green">✓</AppText></View></GlassCard>)}<GlassCard><AppText variant="heading">Статусы качества</AppText><AppText tone="secondary">«Проверено» — внутренняя карточка Точки Роста. «Импортировано» — справочный набор USDA. «Сообщество» — Open Food Facts. «Моё» — данные, которые ввёл пользователь.</AppText></GlassCard><GlassCard><AppText variant="heading">Лицензии и атрибуция</AppText><AppText tone="secondary">USDA FoodData Central — данные правительства США, public domain; в приложении указаны источник и версия выгрузки.</AppText><AppText tone="secondary">Open Food Facts — база ODbL; содержимое базы доступно на условиях Database Contents License, изображения — CC BY-SA. Приложение кеширует только открытый пользователем продукт.</AppText></GlassCard><GlassCard><AppText variant="heading">Важно</AppText><AppText tone="secondary">Значения КБЖУ носят справочный характер и могут отличаться от этикетки. Для упакованных продуктов всегда сверяй данные с конкретной упаковкой.</AppText></GlassCard></TabScreen>; }
const styles = StyleSheet.create({ close: { width: 42, height: 42, borderRadius: radii.pill, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface }, row: { flexDirection: 'row', alignItems: 'center', gap: spacing.md }, copy: { flex: 1, gap: spacing.xs }, bold: { fontWeight: '700' } });
