import { useCallback, useEffect, useState } from 'react';
import Constants from 'expo-constants';
import { Redirect, router } from 'expo-router';
import { Alert, Pressable, StyleSheet, View } from 'react-native';
import { AppText } from '@/components/AppText';
import { GlassCard } from '@/components/GlassCard';
import { PrimaryButton } from '@/components/PrimaryButton';
import { TabScreen } from '@/components/TabScreen';
import { clearDiaryForDevelopment, clearFlowForDevelopment, createTestStreak, inspectDevelopmentDatabase, recalculateAllDiaryAggregates, reseedForDevelopment } from '@/database/repositories/developerRepository';
import { getLocalDataSummary } from '@/database/repositories/dataRepository';
import { useAppStore } from '@/store/appStore';
import { colors, radii, spacing } from '@/theme/tokens';

export default function DeveloperScreen() { const initialize = useAppStore((state) => state.initialize); const [summary, setSummary] = useState<Awaited<ReturnType<typeof getLocalDataSummary>> | null>(null); const [inspection, setInspection] = useState<Awaited<ReturnType<typeof inspectDevelopmentDatabase>> | null>(null); const [busy, setBusy] = useState(false); const refresh = useCallback(async () => { const [nextSummary, nextInspection] = await Promise.all([getLocalDataSummary(), inspectDevelopmentDatabase()]); setSummary(nextSummary); setInspection(nextInspection); }, []); useEffect(() => { if (__DEV__) void refresh(); }, [refresh]); if (!__DEV__) return <Redirect href="/(tabs)/profile"/>;
  const run = async (label: string, action: () => Promise<void>) => { try { setBusy(true); await action(); await initialize(); await refresh(); Alert.alert('Готово', label); } catch (error) { Alert.alert('Ошибка', error instanceof Error ? error.message : 'Операция не выполнена'); } finally { setBusy(false); } };
  const confirm = (title: string, action: () => Promise<void>) => Alert.alert(title, 'Действие изменит только локальные тестовые данные.', [{ text: 'Отмена', style: 'cancel' }, { text: 'Продолжить', style: 'destructive', onPress: () => void run(title, action) }]);
  return <TabScreen title="Диагностика" subtitle="Доступно только в development" headerRight={<Pressable style={styles.close} onPress={() => router.back()}><AppText>×</AppText></Pressable>}><GlassCard><AppText variant="heading">Среда</AppText><AppText tone="secondary">Приложение: {Constants.expoConfig?.version ?? '—'} · Expo SDK {Constants.expoConfig?.sdkVersion ?? '54'}</AppText><AppText tone="secondary">SQLite: v{inspection?.version ?? '—'} · продукты {inspection?.products ?? '—'} · записи {inspection?.entries ?? '—'}</AppText><AppText tone="secondary">Коды: {inspection?.coded ?? '—'} · дубли {inspection?.duplicateCodes ?? '—'}</AppText></GlassCard><GlassCard><AppText variant="heading">Тестовый Поток</AppText><View style={styles.row}>{([3,7,14] as const).map((days) => <View key={days} style={styles.flex}><PrimaryButton label={`${days} дней`} secondary disabled={busy} onPress={() => run(`Создана серия ${days} дней`, () => createTestStreak(days))}/></View>)}</View><PrimaryButton label="Очистить только Поток" secondary disabled={busy} onPress={() => confirm('Очистить Поток?', clearFlowForDevelopment)}/></GlassCard><GlassCard><AppText variant="heading">База и агрегаты</AppText><PrimaryButton label="Пересчитать агрегаты" secondary disabled={busy} onPress={() => run('Агрегаты пересчитаны', recalculateAllDiaryAggregates)}/><PrimaryButton label="Повторить seed" secondary disabled={busy} onPress={() => run('Seed выполнен', reseedForDevelopment)}/><PrimaryButton label="Очистить только дневник" secondary disabled={busy} onPress={() => confirm('Очистить дневник?', clearDiaryForDevelopment)}/></GlassCard><GlassCard><AppText variant="heading">Источники</AppText>{summary?.sources.map((source) => <AppText key={source.source_type} tone="secondary">{source.source_type}: {source.count}</AppText>)}</GlassCard><AppText variant="caption" tone="muted">Все действия локальны. Экран исключён из меню production-сборки и перенаправляет в профиль вне development.</AppText></TabScreen>; }
const styles = StyleSheet.create({ close: { width: 42, height: 42, borderRadius: radii.pill, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.surface }, row: { flexDirection: 'row', gap: spacing.xs }, flex: { flex: 1 } });
