import { useEffect, useState } from 'react';
import { Alert, StyleSheet, View } from 'react-native';
import { router } from 'expo-router';
import { AppText } from '@/components/AppText';
import { GlassCard } from '@/components/GlassCard';
import { PrimaryButton } from '@/components/PrimaryButton';
import { TabScreen } from '@/components/TabScreen';
import { mealLabels } from '@/constants/options';
import { loadBudgetSettings } from '@/database/repositories/budgetRepository';
import { RhythmCharacter } from '@/features/rhythm/components/RhythmCharacter';
import { getRhythmDayPlans, getRhythmRecommendations } from '@/features/rhythm/services/plannerService';
import { recordRhythmFeedback } from '@/features/rhythm/repositories/rhythmRepository';
import type { RhythmRecommendation } from '@/features/rhythm/types/rhythm';
import { getSmartNextStep } from '@/services/smartNextStep';
import { useAppStore } from '@/store/appStore';
import { spacing } from '@/theme/tokens';

export default function RhythmCenterScreen(){const profile=useAppStore(s=>s.profile);const target=useAppStore(s=>s.target);const diary=useAppStore(s=>s.diary);const ensureProductsLoaded=useAppStore(s=>s.ensureProductsLoaded);const addToDiary=useAppStore(s=>s.addToDiary);const diaryDate=useAppStore(s=>s.diaryDate);const[items,setItems]=useState<RhythmRecommendation[]>([]);const[loading,setLoading]=useState(true);const[busy,setBusy]=useState<string|null>(null);const[dayPlans,setDayPlans]=useState<Awaited<ReturnType<typeof getRhythmDayPlans>>>([]);const meal=getSmartNextStep(diary,new Date().getHours()).meal;
  useEffect(()=>{let active=true;if(!profile||!target){setLoading(false);return;}void ensureProductsLoaded().then(async()=>{const state=useAppStore.getState();const budget=await loadBudgetSettings();const remaining={calories:Math.max(0,target.calories-(diary?.consumedCalories??0)),proteinG:Math.max(0,target.proteinG-(diary?.consumedProteinG??0)),fatG:Math.max(0,target.fatG-(diary?.consumedFatG??0)),carbsG:Math.max(0,target.carbsG-(diary?.consumedCarbsG??0))};const next=await getRhythmRecommendations({products:state.products,profile,target,mealType:meal,remaining,budget,usedProductIds:diary?.entries.flatMap(entry=>entry.productId?[entry.productId]:[])??[]});if(active){setItems(next);setLoading(false);}}).catch(()=>{if(active)setLoading(false);});return()=>{active=false;};},[diary,ensureProductsLoaded,meal,profile,target]);
  const accept=async(item:RhythmRecommendation)=>{try{setBusy(item.id);for(const candidate of item.items)await addToDiary({date:diaryDate,product:candidate.product,mealType:meal,servings:candidate.servings,quantityG:candidate.quantityG});await recordRhythmFeedback('accepted',{recommendationKey:item.id,productIds:item.items.map(value=>value.product.id)});Alert.alert('Добавлено',`Вариант добавлен в ${mealLabels[meal].toLocaleLowerCase('ru-RU')}.`);}finally{setBusy(null);}};
  const buildDay=async()=>{if(!profile||!target)return;setBusy('day');const budget=await loadBudgetSettings();try{setDayPlans(await getRhythmDayPlans({products:useAppStore.getState().products,profile,target,budget}));}finally{setBusy(null);}};
  return <TabScreen title="Центр Ритма" subtitle="Локальный подбор — решение всегда за тобой"><GlassCard variant="accent"><View style={styles.hero}><RhythmCharacter size="medium" emotion="thinking" action="presentAdvice"/><View style={styles.grow}><AppText variant="heading">Что подойдёт сейчас</AppText><AppText tone="secondary">Учитываю остаток КБЖУ, ограничения, бюджет, разнообразие и доступные данные.</AppText></View></View></GlassCard>{!profile||!target?<GlassCard><AppText>Сначала заверши профиль, чтобы Ритм мог сравнить варианты.</AppText></GlassCard>:loading?<GlassCard><AppText tone="secondary">Сравниваю доступные продукты…</AppText></GlassCard>:!items.length?<GlassCard><AppText variant="heading">Подходящих вариантов пока нет</AppText><AppText tone="secondary">Я не предлагаю продукты, которые конфликтуют с ограничениями или не имеют достаточных данных.</AppText><PrimaryButton label="Открыть каталог" onPress={()=>router.push('/(tabs)/catalog')}/></GlassCard>:items.map((item,index)=><GlassCard key={item.id} variant={index===0?'accent':'default'}><AppText variant="caption" tone="green">{index===0?'ЛУЧШЕЕ СОВПАДЕНИЕ':'ЕЩЁ ВАРИАНТ'}</AppText><AppText variant="heading">{item.items.map(value=>value.product.name).join(' + ')}</AppText><AppText tone="secondary">{Math.round(item.calories)} ккал · Б {Math.round(item.proteinG)} · Ж {Math.round(item.fatG)} · У {Math.round(item.carbsG)}</AppText><AppText variant="caption" tone="muted">≈ {Math.round(item.price)} ₽ · {item.reasons.join(' · ')}</AppText><PrimaryButton label={busy===item.id?'Добавляем…':'Добавить вариант'} disabled={busy!==null} onPress={()=>accept(item)}/><PrimaryButton label="Не подходит" secondary onPress={async()=>{await recordRhythmFeedback('dismissed',{recommendationKey:item.id,productIds:item.items.map(value=>value.product.id)});setItems(current=>current.filter(value=>value.id!==item.id));}}/></GlassCard>)}<GlassCard><AppText variant="heading">План на день</AppText><AppText tone="secondary">Beam-планировщик сравнит несколько траекторий и покажет разные наборы без автоматического добавления.</AppText><PrimaryButton label={busy==='day'?'Собираю…':'Собрать варианты дня'} secondary disabled={busy!==null} onPress={buildDay}/>{dayPlans.map((plan,index)=><View key={plan.id} style={styles.plan}><AppText style={styles.bold}>Вариант {index+1} · {Math.round(plan.calories)} ккал · ≈ {Math.round(plan.price)} ₽</AppText><AppText variant="caption" tone="muted">{plan.items.map(item=>`${mealLabels[item.mealType]}: ${item.product.name}`).join('\n')}</AppText></View>)}</GlassCard><AppText variant="caption" tone="muted">Рекомендации — ориентир, а не медицинская рекомендация. Расчёты выполняются только на устройстве.</AppText></TabScreen>;
}
const styles=StyleSheet.create({hero:{flexDirection:'row',alignItems:'center',gap:spacing.md},grow:{flex:1},plan:{gap:spacing.xs,paddingTop:spacing.md},bold:{fontWeight:'700'}});
