import { useCallback, useEffect, useRef, useState } from 'react';
import { CameraView, useCameraPermissions, type BarcodeScanningResult } from 'expo-camera';
import { Image } from 'expo-image';
import { router, useFocusEffect } from 'expo-router';
import { Alert, AppState, Pressable, ScrollView, StyleSheet, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { AppBackground } from '@/components/AppBackground';
import { AppBackButton } from '@/components/AppBackButton';
import { AppText } from '@/components/AppText';
import { AppIcon } from '@/components/AppIcon';
import { FormField } from '@/components/FormField';
import { GlassCard } from '@/components/GlassCard';
import { PrimaryButton } from '@/components/PrimaryButton';
import { findProductByCode, saveExternalFoodProduct } from '@/database/repositories/productRepository';
import { cacheExternalFood, getCachedExternalFood, recordScan } from '@/database/repositories/scanRepository';
import { fetchOpenFoodFactsProduct } from '@/services/openFoodFacts';
import { useAppStore } from '@/store/appStore';
import { colors, radii, spacing } from '@/theme/tokens';
import type { ExternalFoodPreview } from '@/types/domain';

const numeric = (value: string) => value.trim() === '' ? null : Number(value.replace(',', '.'));
export default function ScannerScreen() {
  const [permission, requestPermission] = useCameraPermissions(); const refreshProducts = useAppStore((state) => state.refreshProducts);
  const [paused, setPaused] = useState(false); const [torch, setTorch] = useState(false); const [code, setCode] = useState(''); const [manual, setManual] = useState(false); const [loading, setLoading] = useState(false); const [preview, setPreview] = useState<ExternalFoodPreview | null>(null); const lastCode = useRef('');
  const [corrections, setCorrections] = useState({ name: '', serving: '100', calories: '', protein: '', fat: '', carbs: '' });
  const goBack = () => { if (router.canGoBack()) router.back(); else router.replace('/(tabs)/catalog'); };
  useFocusEffect(useCallback(() => {
    if (!preview && !manual) setPaused(false);
    return () => { setTorch(false); setPaused(true); };
  }, [manual, preview]));
  useEffect(() => {
    const subscription = AppState.addEventListener('change', (state) => {
      if (state !== 'active') { setTorch(false); setPaused(true); }
      else if (!preview && !manual) setPaused(false);
    });
    return () => subscription.remove();
  }, [manual, preview]);
  const lookup = async (raw: string) => {
    const value = raw.trim(); if (!value || loading || value === lastCode.current) return; lastCode.current = value; setLoading(true); setPaused(true);
    try { const local = await findProductByCode(value); if (local) { await recordScan(value, local.id); router.replace(`/product/${local.id}` as never); return; }
      const cached = await getCachedExternalFood(value); const external = cached ?? await fetchOpenFoodFactsProduct(value); if (!external) { await recordScan(value, null); Alert.alert('Продукт не найден', 'Введи данные с упаковки вручную — они сохранятся только на устройстве.', [{ text: 'Создать продукт', onPress: () => router.replace('/product/new' as never) }, { text: 'Повторить', onPress: reset }]); return; }
      if (!cached) await cacheExternalFood(external); await recordScan(value, null); setPreview(external); setCorrections({ name: external.name, serving: '100', calories: external.caloriesPer100g?.toString() ?? '', protein: external.proteinPer100g?.toString() ?? '', fat: external.fatPer100g?.toString() ?? '', carbs: external.carbsPer100g?.toString() ?? '' });
    } catch (error) { Alert.alert('Не удалось найти продукт', error instanceof Error ? error.message : 'Попробуй ещё раз', [{ text: 'Ввести вручную', onPress: () => router.replace('/product/new' as never) }, { text: 'Повторить', onPress: reset }]); } finally { setLoading(false); }
  };
  const reset = () => { lastCode.current = ''; setPreview(null); setCode(''); setPaused(false); };
  const scanned = ({ data }: BarcodeScanningResult) => void lookup(data);
  const save = async () => { if (!preview) return; try { setLoading(true); const product = await saveExternalFoodProduct(preview, { name: corrections.name, servingSizeG: numeric(corrections.serving) ?? 100, caloriesPer100g: numeric(corrections.calories), proteinPer100g: numeric(corrections.protein), fatPer100g: numeric(corrections.fat), carbsPer100g: numeric(corrections.carbs) }); await refreshProducts(); if (product) router.replace(`/product/${product.id}` as never); } catch (error) { Alert.alert('Не удалось сохранить', error instanceof Error ? error.message : 'Проверь значения'); } finally { setLoading(false); } };
  if (!permission) return <AppBackground><SafeAreaView style={styles.center}><AppText tone="secondary">Проверяем доступ к камере…</AppText></SafeAreaView></AppBackground>;
  if (!permission.granted) return <AppBackground><SafeAreaView style={styles.permission}><AppBackButton fallbackRoute="/(tabs)/catalog" /><AppText variant="title">Нужен доступ к камере</AppText><AppText tone="secondary" style={styles.centerText}>Камера используется только для распознавания QR-кода или штрихкода. Снимок не сохраняется.</AppText><PrimaryButton label="Разрешить камеру" onPress={async () => { await requestPermission(); }}/><PrimaryButton label="Ввести код вручную" secondary onPress={() => setManual(true)}/><PrimaryButton label="Вернуться в каталог" secondary onPress={goBack}/>{manual ? <ManualCode value={code} setValue={setCode} onLookup={lookup}/> : null}</SafeAreaView></AppBackground>;
  if (preview) return <AppBackground><ScrollView contentContainerStyle={styles.previewContent}><AppText variant="title">Проверь данные</AppText><AppText tone="secondary">Источник: Open Food Facts. Исправь значения с этикетки перед сохранением.</AppText>{preview.imageUrl ? <Image source={{ uri: preview.imageUrl }} contentFit="contain" style={styles.productImage}/> : null}<GlassCard style={styles.form}><FormField label="Название" value={corrections.name} onChangeText={(name) => setCorrections({ ...corrections, name })}/><FormField label="Порция" value={corrections.serving} onChangeText={(serving) => setCorrections({ ...corrections, serving })} keyboardType="decimal-pad" suffix="г"/><FormField label="Калории на 100 г *" value={corrections.calories} onChangeText={(calories) => setCorrections({ ...corrections, calories })} keyboardType="decimal-pad" suffix="ккал"/><FormField label="Белки на 100 г" value={corrections.protein} onChangeText={(protein) => setCorrections({ ...corrections, protein })} keyboardType="decimal-pad" suffix="г"/><FormField label="Жиры на 100 г" value={corrections.fat} onChangeText={(fat) => setCorrections({ ...corrections, fat })} keyboardType="decimal-pad" suffix="г"/><FormField label="Углеводы на 100 г" value={corrections.carbs} onChangeText={(carbs) => setCorrections({ ...corrections, carbs })} keyboardType="decimal-pad" suffix="г"/></GlassCard><PrimaryButton label={loading ? 'Сохраняем…' : 'Сохранить локально'} disabled={loading} onPress={save}/><PrimaryButton label="Сканировать снова" secondary onPress={reset}/></ScrollView></AppBackground>;
  return <View style={styles.cameraPage}><CameraView style={StyleSheet.absoluteFill} facing="back" enableTorch={torch} barcodeScannerSettings={{ barcodeTypes: ['ean13', 'ean8', 'upc_a', 'upc_e', 'qr'] }} onBarcodeScanned={paused ? undefined : scanned}/><SafeAreaView style={styles.overlay}><View style={styles.top}><AppBackButton fallbackRoute="/(tabs)/catalog" style={styles.control} iconColor="#FFFFFF" /><AppText style={styles.topTitle}>Наведи на код</AppText><View style={styles.controlSpacer}/></View><View style={styles.scanArea}><View style={styles.frame}/><Pressable accessibilityRole="switch" accessibilityState={{ checked: torch }} accessibilityLabel={torch ? 'Выключить фонарик' : 'Включить фонарик'} onPress={() => setTorch((value) => !value)} style={[styles.torchButton, torch && styles.torchButtonActive]}><AppIcon name="torch" size={28} color={torch ? colors.greenDark : '#FFFFFF'}/></Pressable><AppText style={styles.torchLabel}>{torch ? 'Фонарик включён' : 'Фонарик'}</AppText></View><View style={styles.bottom}><AppText style={styles.centerText}>{loading ? 'Ищем продукт…' : 'Код распознаётся автоматически'}</AppText><PrimaryButton label="Ввести код вручную" secondary onPress={() => { setManual(!manual); setPaused(true); setTorch(false); }}/>{manual ? <ManualCode value={code} setValue={setCode} onLookup={lookup}/> : null}</View></SafeAreaView></View>;
}
function ManualCode({ value, setValue, onLookup }: { value: string; setValue: (value: string) => void; onLookup: (value: string) => Promise<void> }) { return <View style={styles.manual}><TextInput value={value} onChangeText={setValue} keyboardType="number-pad" placeholder="8–14 цифр" placeholderTextColor={colors.textMuted} style={styles.manualInput}/><PrimaryButton label="Найти" onPress={() => onLookup(value)}/></View>; }
const styles = StyleSheet.create({ cameraPage: { flex: 1, backgroundColor: '#000' }, overlay: { flex: 1, justifyContent: 'space-between', padding: spacing.lg }, top: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, topTitle: { fontWeight: '800', textShadowColor: '#000', textShadowRadius: 8 }, control: { width: 46, height: 46, alignItems: 'center', justifyContent: 'center', borderRadius: radii.pill, backgroundColor: 'rgba(0,0,0,.55)' }, controlSpacer: { width: 46, height: 46 }, scanArea: { alignItems: 'center', gap: spacing.sm }, frame: { alignSelf: 'center', width: '82%', aspectRatio: 1.55, borderWidth: 3, borderColor: colors.greenBright, borderRadius: radii.lg, backgroundColor: 'transparent' }, torchButton: { width: 64, height: 64, marginTop: spacing.sm, alignItems: 'center', justifyContent: 'center', borderRadius: radii.pill, borderWidth: 1, borderColor: 'rgba(255,255,255,.3)', backgroundColor: 'rgba(0,0,0,.68)' }, torchButtonActive: { borderColor: colors.greenBright, backgroundColor: colors.greenBright }, torchLabel: { fontSize: 13, fontWeight: '700', textShadowColor: '#000', textShadowRadius: 8 }, bottom: { gap: spacing.md, padding: spacing.md, borderRadius: radii.lg, backgroundColor: 'rgba(0,0,0,.62)' }, center: { flex: 1, alignItems: 'center', justifyContent: 'center' }, permission: { flex: 1, justifyContent: 'center', padding: spacing.lg, gap: spacing.lg }, centerText: { textAlign: 'center' }, manual: { gap: spacing.sm }, manualInput: { minHeight: 54, paddingHorizontal: spacing.md, color: colors.textPrimary, fontSize: 18, textAlign: 'center', borderRadius: radii.md, borderWidth: 1, borderColor: colors.glassBorder, backgroundColor: colors.surfaceStrong }, previewContent: { padding: spacing.lg, paddingTop: 64, paddingBottom: 60, gap: spacing.md }, productImage: { width: '100%', height: 190, borderRadius: radii.lg, backgroundColor: '#fff' }, form: { gap: spacing.md } });
