export const betaChecklist = [
  { id: 'first-launch', label: 'Первый запуск' },
  { id: 'choose-goal', label: 'Выбор цели' },
  { id: 'enter-profile', label: 'Ввод параметров' },
  { id: 'personal-result', label: 'Получение ориентира' },
  { id: 'first-entry', label: 'Первая запись' },
  { id: 'home', label: 'Главная' },
  { id: 'diary', label: 'Дневник' },
  { id: 'catalog', label: 'Каталог' },
  { id: 'portion', label: 'Изменение порции' },
  { id: 'qr', label: 'QR' },
  { id: 'torch', label: 'Фонарик' },
  { id: 'rhythm', label: 'Ритм' },
  { id: 'flow', label: 'Поток' },
  { id: 'settings', label: 'Настройки' },
  { id: 'light-theme', label: 'Светлая тема' },
  { id: 'dark-theme', label: 'Тёмная тема' },
  { id: 'restart', label: 'Перезапуск' },
  { id: 'lifecycle', label: 'Background / foreground' },
  { id: 'persistence', label: 'Сохранение данных' },
  { id: 'feedback', label: 'Отправка отзыва' },
] as const;
