import { useEffect, useMemo, useState } from 'react';
import * as Haptics from 'expo-haptics';
import { Modal, Pressable, StyleSheet, View } from 'react-native';
import { Gesture, GestureDetector } from 'react-native-gesture-handler';
import Animated, { runOnJS, useAnimatedStyle, useReducedMotion, useSharedValue, withSpring } from 'react-native-reanimated';
import { loadCalendarMonth } from '@/database/repositories/calendarRepository';
import { buildMonthGrid, formatMonthTitle, getCalendarAccessibilityLabel, shiftMonth } from '@/services/calendar';
import { getLocalDateKey } from '@/utils/date';
import type { CalendarDayStatus } from '@/types/domain';
import { useTheme } from '@/theme/ThemeProvider';
import { motion, radii, spacing } from '@/theme/tokens';
import { AppText } from './AppText';import{PrimaryButton}from'./PrimaryButton';
const weekdays=['Пн','Вт','Ср','Чт','Пт','Сб','Вс'];
export function MonthCalendar({monthKey,selectedDate,statuses,onSelect,onMonthChange,compact=false}:{monthKey:string;selectedDate?:string;statuses:CalendarDayStatus[];onSelect?:(date:string)=>void;onMonthChange?:(month:string)=>void;compact?:boolean}){const{colors}=useTheme();const today=getLocalDateKey();const cells=useMemo(()=>buildMonthGrid(monthKey),[monthKey]);const statusMap=useMemo(()=>new Map(statuses.map((item)=>[item.date,item])),[statuses]);return <View accessible={false}><View style={styles.week}>{weekdays.map((day)=><AppText key={day} variant="caption" tone="muted" style={styles.weekday}>{day}</AppText>)}</View><View style={styles.grid}>{cells.map((cell)=>{const status=statusMap.get(cell.date);const selected=selectedDate===cell.date;const isToday=cell.date===today;return <Pressable key={cell.date} accessibilityRole="button" accessibilityLabel={getCalendarAccessibilityLabel(cell,status,selected,today)} accessibilityState={{selected}} onPress={()=>{if(!cell.inCurrentMonth)onMonthChange?.(cell.date.slice(0,7));onSelect?.(cell.date);}} style={[styles.cell,compact&&styles.compactCell,selected&&{backgroundColor:colors.greenPrimary},isToday&&!selected&&{borderColor:colors.greenBright,borderWidth:1},status?.isMilestone&&{borderColor:colors.gold,borderWidth:1}]}><AppText variant="caption" tone={selected?'primary':cell.inCurrentMonth?'secondary':'muted'} style={selected&&styles.selectedText}>{cell.day}</AppText><View style={styles.markers}>{status?.isCompleted?<AppText style={[styles.flame,{color:status.isMilestone?colors.gold:colors.greenBright}]}>◆</AppText>:status?.entryCount?<View style={[styles.dot,{backgroundColor:colors.greenBright}]}/>:status?.kind==='missed'?<View style={[styles.dot,{backgroundColor:colors.textMuted,opacity:.35}]}/>:null}{status?.isPaused?<View style={[styles.pause,{borderColor:colors.gold}]}/>:null}</View></Pressable>;})}</View></View>;}
export function DiaryCalendarSheet({visible,selectedDate,onClose,onOpen}:{visible:boolean;selectedDate:string;onClose:()=>void;onOpen:(date:string)=>void}){const{colors}=useTheme();const[month,setMonth]=useState(selectedDate.slice(0,7));const[selected,setSelected]=useState(selectedDate);const[statuses,setStatuses]=useState<CalendarDayStatus[]>([]);const y=useSharedValue(0);const reduced=useReducedMotion();useEffect(()=>{if(visible){setSelected(selectedDate);setMonth(selectedDate.slice(0,7));}},[selectedDate,visible]);useEffect(()=>{if(visible)void loadCalendarMonth(month).then(setStatuses);},[month,visible]);const dismiss=()=>{y.value=0;onClose();};const drag=Gesture.Pan().activeOffsetY(12).onUpdate((event)=>{y.value=Math.max(0,event.translationY);}).onEnd((event)=>{if(event.translationY>90||event.velocityY>750)runOnJS(dismiss)();else y.value=withSpring(0,motion.spring.soft);});const swipe=Gesture.Pan().activeOffsetX([-18,18]).failOffsetY([-12,12]).onEnd((event)=>{if(Math.abs(event.translationX)>55)runOnJS(setMonth)(shiftMonth(month,event.translationX<0?1:-1));});const animated=useAnimatedStyle(()=>({transform:[{translateY:reduced?0:y.value}]}));return <Modal visible={visible} transparent animationType={reduced?'none':'fade'} onRequestClose={dismiss}><Pressable style={[styles.scrim,{backgroundColor:colors.blackScrim}]} onPress={dismiss}/><GestureDetector gesture={drag}><Animated.View style={[styles.sheet,{backgroundColor:colors.surfaceSolid,borderColor:colors.glassBorderStrong},animated]}><View style={[styles.handle,{backgroundColor:colors.textMuted}]}/><View style={styles.header}><Pressable accessibilityLabel="Предыдущий месяц" style={[styles.arrow,{backgroundColor:colors.surface}]} onPress={()=>setMonth(shiftMonth(month,-1))}><AppText>‹</AppText></Pressable><View style={styles.title}><AppText variant="heading">{formatMonthTitle(month)}</AppText><Pressable onPress={()=>{const today=getLocalDateKey();setSelected(today);setMonth(today.slice(0,7));}}><AppText variant="caption" tone="green">Сегодня</AppText></Pressable></View><Pressable accessibilityLabel="Следующий месяц" style={[styles.arrow,{backgroundColor:colors.surface}]} onPress={()=>setMonth(shiftMonth(month,1))}><AppText>›</AppText></Pressable></View><GestureDetector gesture={swipe}><View><MonthCalendar monthKey={month} selectedDate={selected} statuses={statuses} onSelect={(date)=>{void Haptics.selectionAsync();setSelected(date);}} onMonthChange={setMonth}/></View></GestureDetector><View style={styles.legend}><AppText variant="caption" tone="muted">● запись</AppText><AppText variant="caption" tone="muted">◆ закрыт</AppText><AppText variant="caption" style={{color:colors.gold}}>◇ этап / пауза</AppText></View><PrimaryButton label="Открыть выбранный день" onPress={()=>{onOpen(selected);dismiss();}}/></Animated.View></GestureDetector></Modal>;}
const styles=StyleSheet.create({scrim:{...StyleSheet.absoluteFillObject},sheet:{position:'absolute',left:0,right:0,bottom:0,minHeight:'70%',maxHeight:'86%',borderTopLeftRadius:radii.xl,borderTopRightRadius:radii.xl,borderWidth:1,paddingHorizontal:spacing.lg,paddingTop:spacing.sm,paddingBottom:40,gap:spacing.md},handle:{width:42,height:5,borderRadius:3,alignSelf:'center',opacity:.45},header:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},arrow:{width:44,height:44,borderRadius:22,alignItems:'center',justifyContent:'center'},title:{alignItems:'center',gap:3},week:{flexDirection:'row'},weekday:{width:`${100/7}%`,textAlign:'center'},grid:{flexDirection:'row',flexWrap:'wrap',marginTop:spacing.xs},cell:{width:`${100/7}%`,aspectRatio:1,alignItems:'center',justifyContent:'center',borderRadius:radii.pill},compactCell:{aspectRatio:1.08},selectedText:{color:'#031108',fontWeight:'800'},markers:{height:9,flexDirection:'row',alignItems:'center',gap:2},dot:{width:4,height:4,borderRadius:2},flame:{fontSize:7},pause:{width:6,height:6,borderRadius:3,borderWidth:1},legend:{flexDirection:'row',justifyContent:'center',gap:spacing.md}});
