import { inflateSync } from 'node:zlib';
import { readFileSync, statSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, expect, it } from 'vitest';

const read=(file:string)=>readFileSync(resolve(process.cwd(),file),'utf8');

function decodePngAlpha(file:string){
  const png=readFileSync(resolve(process.cwd(),file));let offset=8;let width=0;let height=0;let colorType=0;const chunks:Buffer[]=[];
  while(offset<png.length){const length=png.readUInt32BE(offset);const type=png.toString('ascii',offset+4,offset+8);const data=png.subarray(offset+8,offset+8+length);if(type==='IHDR'){width=data.readUInt32BE(0);height=data.readUInt32BE(4);expect(data[8]).toBe(8);colorType=data[9];}if(type==='IDAT')chunks.push(data);offset+=length+12;if(type==='IEND')break;}
  expect(colorType).toBe(6);const packed=inflateSync(Buffer.concat(chunks));const bytesPerPixel=4;const stride=width*bytesPerPixel;const pixels=Buffer.alloc(stride*height);const paeth=(a:number,b:number,c:number)=>{const p=a+b-c;const pa=Math.abs(p-a),pb=Math.abs(p-b),pc=Math.abs(p-c);return pa<=pb&&pa<=pc?a:pb<=pc?b:c;};
  for(let y=0;y<height;y+=1){const source=y*(stride+1);const filter=packed[source];for(let x=0;x<stride;x+=1){const raw=packed[source+1+x];const left=x>=bytesPerPixel?pixels[y*stride+x-bytesPerPixel]:0;const up=y?pixels[(y-1)*stride+x]:0;const upperLeft=y&&x>=bytesPerPixel?pixels[(y-1)*stride+x-bytesPerPixel]:0;const value=filter===0?raw:filter===1?raw+left:filter===2?raw+up:filter===3?raw+Math.floor((left+up)/2):raw+paeth(left,up,upperLeft);pixels[y*stride+x]=value&255;}}
  const alpha=(x:number,y:number)=>pixels[y*stride+x*4+3];let minX=width,minY=height,maxX=-1,maxY=-1;for(let y=0;y<height;y+=1)for(let x=0;x<width;x+=1)if(alpha(x,y)>8){minX=Math.min(minX,x);minY=Math.min(minY,y);maxX=Math.max(maxX,x);maxY=Math.max(maxY,y);}return{width,height,cornerAlpha:[alpha(0,0),alpha(width-1,0),alpha(0,height-1),alpha(width-1,height-1)],bounds:{minX,minY,maxX,maxY}};
}

describe('diary date header regression',()=>{
  it('removes the unsupported glyph and keeps a symmetric three-part header',()=>{const diary=read('src/app/(tabs)/diary.tsx');const header=read('src/components/DiaryDateHeader.tsx');expect(diary).not.toContain('▣');expect(header).not.toMatch(/[□▣▢]/);expect(header).toContain('testID="diary-date-header"');expect(header).toContain("dateCopy: { flex: 1");expect(header).toContain("arrow: { width: 44, height: 44");expect(header).toContain('onChangeDay(-1)');expect(header).toContain('onChangeDay(1)');});
  it('opens the existing calendar from the whole accessible date block',()=>{const diary=read('src/app/(tabs)/diary.tsx');const header=read('src/components/DiaryDateHeader.tsx');expect(diary).toContain('onOpenCalendar={()=>setCalendar(true)}');expect(diary).toContain('<DiaryCalendarSheet visible');expect(header).toContain('accessibilityRole="button"');expect(header).toContain('accessibilityLabel="Открыть календарь"');expect(header).toContain('accessibilityHint="Выбрать другую дату"');expect(header).toContain('haptic="selection"');expect(header).toContain('minHeight: 52');expect(header).toContain('datePressed: { opacity: 0.86 }');});
  it('uses project SVG icons instead of text glyphs for diary actions',()=>{const diary=read('src/app/(tabs)/diary.tsx');const calendar=read('src/components/DiaryCalendarSheet.tsx');for(const glyph of ['⇥','▦','＋','<AppText>‹</AppText>','<AppText>›</AppText>'])expect(diary+calendar).not.toContain(glyph);expect(diary).toContain('<AppIcon name="copy"');expect(diary).toContain('<AppIcon name="collection"');expect(diary).toContain('<AppIcon name="add"');});
});

describe('unified volumetric Rhythm assets',()=>{
  const component=read('src/features/rhythm/components/RhythmCharacter.tsx');const config=read('src/features/rhythm/config/rhythmAssets.ts');
  it('uses Expo Image and never returns the former flat SVG fallback',()=>{expect(component).toContain("from 'expo-image'");expect(component).toContain('cachePolicy="memory-disk"');expect(component).toContain('contentFit="contain"');expect(component).toContain('useMemo(()=>resolveRhythmAsset');expect(component).not.toContain('VectorRhythm');expect(component).not.toContain('react-native-svg');expect(read('src/features/rhythm/components/RhythmSuggestionCard.tsx')).toContain('<RhythmCharacter');expect(read('src/features/rhythm/components/RhythmSuggestionCard.tsx')).not.toContain('preferIllustration');});
  it('keeps stable compact medium and hero sources outside render',()=>{expect(config).toContain("rhythm-idle-compact.png");expect(config).toContain("rhythm-idle-medium.png");expect(config).toContain("rhythm-idle-hero.png");expect(config).not.toMatch(/require\([^\n]*rhythm-idle\.png/);expect(config).toContain('const exact=');expect(config).toContain('sameEmotionMedium');expect(config).toContain('idleForSize');});
  it('stores optimized transparent assets with safe padding',()=>{const files=[['assets/rhythm/rhythm-idle-compact.png',256,100_000],['assets/rhythm/rhythm-idle-medium.png',512,200_000],['assets/rhythm/rhythm-idle-hero.png',1024,500_000]] as const;for(const[file,longSide,maxBytes]of files){const image=decodePngAlpha(file);expect(Math.max(image.width,image.height)).toBe(longSide);expect(statSync(resolve(process.cwd(),file)).size).toBeLessThan(maxBytes);expect(image.cornerAlpha).toEqual([0,0,0,0]);expect(image.bounds.minX).toBeGreaterThan(0);expect(image.bounds.minY).toBeGreaterThan(0);expect(image.bounds.maxX).toBeLessThan(image.width-1);expect(image.bounds.maxY).toBeLessThan(image.height-1);}});
  it('stops animation outside focus and stays static in reduced or Safe Mode',()=>{expect(component).toContain('activity.canAnimate');expect(component).toContain('cancelAnimation(breathe)');expect(component).toContain('cancelAnimation(react)');expect(read('src/hooks/useScreenActivity.ts')).toContain("resolvedPerformanceMode !== 'safe'");expect(read('src/hooks/useScreenActivity.ts')).toContain('!reducedMotion');});
  it('falls back to a volumetric idle render and then the brand flame icon without crashing',()=>{expect(component).toContain('rhythmAssets.idle.compact');expect(component).toContain("setErrorStage(stage=>stage===0?1:2)");expect(component).toContain('<AppIcon name="flow"');expect(component).toContain('console.warn(`[RhythmCharacter] Failed to load');});
  it('keeps the Flow copy and loads only the currently resolved asset',()=>{const flow=read('src/app/(tabs)/flow.tsx');expect(flow).toContain('Давай найдём твой ритм');expect(flow).toContain('Начни с одной записи — идеальный день не нужен.');expect(component).toContain('source={visibleAsset.source}');expect(component).not.toContain('rhythmEmotionValues.map');});
});

