import { useCallback, useMemo } from 'react';
import { router, useFocusEffect } from 'expo-router';
import { StyleSheet, View } from 'react-native';
import { AppIcon } from '@/components/AppIcon';
import { AppText } from '@/components/AppText';
import { GlassCard } from '@/components/GlassCard';
import { PrimaryButton } from '@/components/PrimaryButton';
import { TabScreen } from '@/components/TabScreen';
import { useAppStore } from '@/store/appStore';
import { colors, radii, spacing } from '@/theme/tokens';
import { getLocalDateKey } from '@/utils/date';

const milestones = [3, 7, 14, 30, 60, 100];
export default function FlowScreen() { const flow = useAppStore((state) => state.flow); const refresh = useAppStore((state) => state.refreshFlow); useFocusEffect(useCallback(() => { void refresh(); }, [refresh])); const days = useMemo(() => { const today = new Date(); const year = today.getFullYear(); const month = today.getMonth(); const first = new Date(year, month, 1); const padding = (first.getDay() + 6) % 7; const count = new Date(year, month + 1, 0).getDate(); return [...Array(padding).fill(null), ...Array.from({ length: count }, (_, index) => getLocalDateKey(new Date(year, month, index + 1)))]; }, []); const next = milestones.find((value) => value > (flow?.currentStreak ?? 0)) ?? 100; return <TabScreen title="Поток" subtitle="Регулярность, а не идеальность"><GlassCard variant="accent" style={styles.hero}><AppIcon name="flow" size={76} color={colors.greenBright}/><AppText variant="display">{flow?.currentStreak ?? 0} дней</AppText><AppText tone="secondary" style={styles.center}>{flow?.currentStreak ? 'Текущая серия закрытых дней' : 'Закрой день в дневнике, чтобы начать серию.'}</AppText></GlassCard><View style={styles.stats}><GlassCard variant="compact" style={styles.stat}><AppText variant="title">{flow?.longestStreak ?? 0}</AppText><AppText variant="caption" tone="secondary">лучшая серия</AppText></GlassCard><GlassCard variant="compact" style={styles.stat}><AppText variant="title">{flow?.completedDays ?? 0}</AppText><AppText variant="caption" tone="secondary">дней закрыто</AppText></GlassCard></View><GlassCard><AppText variant="heading">Этот месяц</AppText><View style={styles.week}>{['Пн','Вт','Ср','Чт','Пт','Сб','Вс'].map((day) => <AppText key={day} variant="caption" tone="muted" style={styles.day}>{day}</AppText>)}</View><View style={styles.calendar}>{days.map((date, index) => <View key={`${date}-${index}`} style={[styles.cell, date && flow?.completedDates.includes(date) && styles.completed]}>{date ? <AppText variant="caption" tone={flow?.completedDates.includes(date) ? 'green' : 'secondary'}>{Number(date.slice(8))}</AppText> : null}</View>)}</View></GlassCard><GlassCard><View style={styles.headingRow}><AppText variant="heading">Точки пути</AppText><AppText variant="caption" tone="green">следующая — {next}</AppText></View><View style={styles.road}>{milestones.map((day) => <View key={day} style={[styles.point, (flow?.longestStreak ?? 0) >= day && styles.pointDone]}><AppText variant="caption" tone={(flow?.longestStreak ?? 0) >= day ? 'green' : 'muted'}>{day}</AppText></View>)}</View></GlassCard><PrimaryButton label="Открыть аналитику" secondary onPress={() => router.push('/analytics' as never)}/></TabScreen>; }
const styles = StyleSheet.create({ hero: { alignItems: 'center', gap: spacing.sm, paddingVertical: spacing.xl }, center: { textAlign: 'center' }, stats: { flexDirection: 'row', gap: spacing.sm }, stat: { flex: 1, alignItems: 'center' }, week: { flexDirection: 'row', marginTop: spacing.md }, day: { width: `${100/7}%`, textAlign: 'center' }, calendar: { flexDirection: 'row', flexWrap: 'wrap', marginTop: spacing.sm }, cell: { width: `${100/7}%`, aspectRatio: 1, alignItems: 'center', justifyContent: 'center', borderRadius: radii.pill }, completed: { backgroundColor: colors.greenGlow, borderWidth: 1, borderColor: colors.glassBorderStrong }, headingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, road: { flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.lg }, point: { width: 42, height: 42, borderRadius: 21, alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: colors.glassBorder }, pointDone: { backgroundColor: colors.greenGlow, borderColor: colors.glassBorderStrong } });
